# Generated by Django 5.2.8 on 2025-12-12 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentary', '0002_documentary_audio_documentary_published_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Documentary',
        ),
    ]
